//------------------------------------------------------------------------------
// Generated by UIGen as workaround for "Custom Tool" laziness. Will be
// overwritten when user saves corresponding .ascx or .aspx file!
//------------------------------------------------------------------------------

namespace $PROJECT_ROOTNAMESPACE$.UI
{
	public partial class Edit$DOMAIN_CLASSNAME$Control
	{
		protected global::Remotion.ObjectBinding.Web.UI.Controls.BindableObjectDataSourceControl CurrentObject;
		protected global::Remotion.Web.UI.Controls.FormGridManager FormGridManager;
		protected global::System.Web.UI.HtmlControls.HtmlTable $DOMAIN_CLASSNAME$FormGrid;
		// protected Remotion.Web.UI.Controls.FormGridLabel $DOMAIN_CLASSNAME$GridLabel;

    $REPEAT_FOREACHREFERENCEDPROPERTY_BEGIN$(isList=true)
	    protected global::Remotion.Web.UI.Controls.SmartLabel $DOMAIN_PROPERTYNAME$Label;
	    protected global::Remotion.ObjectBinding.Web.UI.Controls.BocList $DOMAIN_PROPERTYNAME$Field;
    $REPEAT_FOREACHREFERENCEDPROPERTY_END$
	}
}
