//------------------------------------------------------------------------------
// Generated by UIGen as workaround for "Custom Tool" laziness. Will be
// overwritten when user saves corresponding .ascx or .aspx file!
//------------------------------------------------------------------------------

namespace $PROJECT_ROOTNAMESPACE$.UI
{
	public partial class Edit$DOMAIN_CLASSNAME$Form
	{
		protected global::Remotion.Web.UI.Controls.HtmlHeadContents HtmlHeadContents;
		protected global::Remotion.ObjectBinding.Web.UI.Controls.BindableObjectDataSourceControl CurrentObject;
                protected global::Remotion.Web.UI.Controls.TabbedMultiView MultiView;
		protected global::$PROJECT_ROOTNAMESPACE$.UI.NavigationTabs TheNavigationTabs;
		protected global::Remotion.Web.UI.Controls.TabView Edit$DOMAIN_CLASSNAME$View;
		protected global::$PROJECT_ROOTNAMESPACE$.UI.Edit$DOMAIN_CLASSNAME$Control Edit$DOMAIN_CLASSNAME$Control;
		protected global::System.Web.UI.HtmlControls.HtmlForm ThisForm;
		protected global::Remotion.Web.UI.Controls.WebButton SaveButton;
		protected global::Remotion.Web.UI.Controls.WebButton CancelButton;
	}
}
