//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneBook.Web.UI {
    using System;
    using System.Collections.Generic;
    using Remotion.Data.DomainObjects;
    using Remotion.Web.ExecutionEngine;
    using Remotion.Web.UI.Globalization;
    using Remotion.ObjectBinding.Web.UI.Controls;
    using Remotion.Web.UI.Controls;
    using PhoneBook.Web;
    using PhoneBook.Web.Classes;
    using PhoneBook.Domain;
    
    
    public partial class EditLocationForm {
        
        protected new EditLocationFormFunction CurrentFunction {
            get {
                return ((EditLocationFormFunction)(base.CurrentFunction));
            }
        }
        
        public Location obj {
            get {
                return ((Location)(this.Variables["obj"]));
            }
            set {
                this.Variables["obj"] = value;
            }
        }
        
        public ObjectID ReturnValue {
            set {
                this.Variables["ReturnValue"] = value;
            }
        }
        
        protected void Return() {
            this.ExecuteNextStep();
        }
        
        public static ObjectID Call(Remotion.Web.ExecutionEngine.IWxePage currentPage, Remotion.Web.ExecutionEngine.IWxeCallArguments arguments, Location obj) {
            EditLocationFormFunction function;
            if ((currentPage.IsReturningPostBack == false)) {
                function = new EditLocationFormFunction(obj);
                function.ExceptionHandler.SetCatchExceptionTypes(typeof(System.Exception));
                currentPage.ExecuteFunction(function, arguments);
                throw new System.Exception("(Unreachable code)");
            }
            else {
                function = ((EditLocationFormFunction)(currentPage.ReturningFunction));
                if ((function.ExceptionHandler.Exception != null)) {
                    throw function.ExceptionHandler.Exception;
                }
                return function.ReturnValue;
            }
        }
        
        public static ObjectID Call(Remotion.Web.ExecutionEngine.IWxePage currentPage, Location obj) {
            return EditLocationForm.Call(currentPage, Remotion.Web.ExecutionEngine.WxeCallArguments.Default, obj);
        }
    }
    
    [System.SerializableAttribute()]
    public class EditLocationFormFunction : PhoneBook.Web.Classes.BaseFunction {
        
        private Remotion.Web.ExecutionEngine.WxePageStep Step1 = new Remotion.Web.ExecutionEngine.WxePageStep("UI\\EditLocationForm.aspx");
        
        public EditLocationFormFunction() : 
                base(new object[0]) {
        }
        
        public EditLocationFormFunction(Location obj) : 
                base(new object[] {
                            obj}) {
        }
        
        [Remotion.Web.ExecutionEngine.WxeParameterAttribute(0, Remotion.Web.ExecutionEngine.WxeParameterDirection.In)]
        public Location obj {
            set {
                this.Variables["obj"] = value;
            }
        }
        
        [Remotion.Web.ExecutionEngine.WxeParameterAttribute(1, Remotion.Web.ExecutionEngine.WxeParameterDirection.Out)]
        public ObjectID ReturnValue {
            get {
                return ((ObjectID)(this.Variables["ReturnValue"]));
            }
        }
    }
}
namespace PhoneBook.Web.UI {
    using System;
    using System.Collections.Generic;
    using Remotion.Data.DomainObjects;
    using Remotion.Web.ExecutionEngine;
    using Remotion.Web.UI.Globalization;
    using Remotion.ObjectBinding.Web.UI.Controls;
    using Remotion.Web.UI.Controls;
    using PhoneBook.Web;
    using PhoneBook.Web.Classes;
    using PhoneBook.Domain;
    
    
    public partial class EditPersonForm {
        
        protected new EditPersonFormFunction CurrentFunction {
            get {
                return ((EditPersonFormFunction)(base.CurrentFunction));
            }
        }
        
        public Person obj {
            get {
                return ((Person)(this.Variables["obj"]));
            }
            set {
                this.Variables["obj"] = value;
            }
        }
        
        protected void Return() {
            this.ExecuteNextStep();
        }
        
        public static void Call(Remotion.Web.ExecutionEngine.IWxePage currentPage, Remotion.Web.ExecutionEngine.IWxeCallArguments arguments, Person obj) {
            EditPersonFormFunction function;
            if ((currentPage.IsReturningPostBack == false)) {
                function = new EditPersonFormFunction(obj);
                function.ExceptionHandler.SetCatchExceptionTypes(typeof(System.Exception));
                currentPage.ExecuteFunction(function, arguments);
                throw new System.Exception("(Unreachable code)");
            }
            else {
                function = ((EditPersonFormFunction)(currentPage.ReturningFunction));
                if ((function.ExceptionHandler.Exception != null)) {
                    throw function.ExceptionHandler.Exception;
                }
            }
        }
        
        public static void Call(Remotion.Web.ExecutionEngine.IWxePage currentPage, Person obj) {
            EditPersonForm.Call(currentPage, Remotion.Web.ExecutionEngine.WxeCallArguments.Default, obj);
        }
    }
    
    [System.SerializableAttribute()]
    public class EditPersonFormFunction : PhoneBook.Web.Classes.BaseFunction {
        
        private Remotion.Web.ExecutionEngine.WxePageStep Step1 = new Remotion.Web.ExecutionEngine.WxePageStep("UI\\EditPersonForm.aspx");
        
        public EditPersonFormFunction() : 
                base(new object[0]) {
        }
        
        public EditPersonFormFunction(Person obj) : 
                base(new object[] {
                            obj}) {
        }
        
        [Remotion.Web.ExecutionEngine.WxeParameterAttribute(0, Remotion.Web.ExecutionEngine.WxeParameterDirection.In)]
        public Person obj {
            set {
                this.Variables["obj"] = value;
            }
        }
    }
}
namespace PhoneBook.Web.UI {
    using System;
    using System.Collections.Generic;
    using Remotion.Data.DomainObjects;
    using Remotion.Web.ExecutionEngine;
    using Remotion.Web.UI.Globalization;
    using Remotion.ObjectBinding.Web.UI.Controls;
    using Remotion.Web.UI.Controls;
    using PhoneBook.Web;
    using PhoneBook.Web.Classes;
    using PhoneBook.Domain;
    
    
    public partial class EditPhoneNumberForm {
        
        protected new EditPhoneNumberFormFunction CurrentFunction {
            get {
                return ((EditPhoneNumberFormFunction)(base.CurrentFunction));
            }
        }
        
        public PhoneNumber obj {
            get {
                return ((PhoneNumber)(this.Variables["obj"]));
            }
            set {
                this.Variables["obj"] = value;
            }
        }
        
        protected void Return() {
            this.ExecuteNextStep();
        }
        
        public static void Call(Remotion.Web.ExecutionEngine.IWxePage currentPage, Remotion.Web.ExecutionEngine.IWxeCallArguments arguments, PhoneNumber obj) {
            EditPhoneNumberFormFunction function;
            if ((currentPage.IsReturningPostBack == false)) {
                function = new EditPhoneNumberFormFunction(obj);
                function.ExceptionHandler.SetCatchExceptionTypes(typeof(System.Exception));
                currentPage.ExecuteFunction(function, arguments);
                throw new System.Exception("(Unreachable code)");
            }
            else {
                function = ((EditPhoneNumberFormFunction)(currentPage.ReturningFunction));
                if ((function.ExceptionHandler.Exception != null)) {
                    throw function.ExceptionHandler.Exception;
                }
            }
        }
        
        public static void Call(Remotion.Web.ExecutionEngine.IWxePage currentPage, PhoneNumber obj) {
            EditPhoneNumberForm.Call(currentPage, Remotion.Web.ExecutionEngine.WxeCallArguments.Default, obj);
        }
    }
    
    [System.SerializableAttribute()]
    public class EditPhoneNumberFormFunction : PhoneBook.Web.Classes.BaseFunction {
        
        private Remotion.Web.ExecutionEngine.WxePageStep Step1 = new Remotion.Web.ExecutionEngine.WxePageStep("UI\\EditPhoneNumberForm.aspx");
        
        public EditPhoneNumberFormFunction() : 
                base(new object[0]) {
        }
        
        public EditPhoneNumberFormFunction(PhoneNumber obj) : 
                base(new object[] {
                            obj}) {
        }
        
        [Remotion.Web.ExecutionEngine.WxeParameterAttribute(0, Remotion.Web.ExecutionEngine.WxeParameterDirection.In)]
        public PhoneNumber obj {
            set {
                this.Variables["obj"] = value;
            }
        }
    }
}
namespace PhoneBook.Web.UI {
    using System;
    using System.Linq;
    using PhoneBook.Web.Classes;
    using Remotion.Data.DomainObjects.Queries;
    using Remotion.ObjectBinding.Web.UI.Controls;
    using Remotion.Web.ExecutionEngine;
    using Remotion.Web.UI.Globalization;
    using PhoneBook.Domain;
    
    
    public partial class PickLocation {
        
        protected new PickLocationFunction CurrentFunction {
            get {
                return ((PickLocationFunction)(base.CurrentFunction));
            }
        }
        
        public Location ReturnValue {
            set {
                this.Variables["ReturnValue"] = value;
            }
        }
        
        public Location[] items {
            get {
                return ((Location[])(this.Variables["items"]));
            }
            set {
                this.Variables["items"] = value;
            }
        }
        
        protected void Return() {
            this.ExecuteNextStep();
        }
        
        public static Location Call(Remotion.Web.ExecutionEngine.IWxePage currentPage, Remotion.Web.ExecutionEngine.IWxeCallArguments arguments) {
            PickLocationFunction function;
            if ((currentPage.IsReturningPostBack == false)) {
                function = new PickLocationFunction();
                function.ExceptionHandler.SetCatchExceptionTypes(typeof(System.Exception));
                currentPage.ExecuteFunction(function, arguments);
                throw new System.Exception("(Unreachable code)");
            }
            else {
                function = ((PickLocationFunction)(currentPage.ReturningFunction));
                if ((function.ExceptionHandler.Exception != null)) {
                    throw function.ExceptionHandler.Exception;
                }
                return function.ReturnValue;
            }
        }
        
        public static Location Call(Remotion.Web.ExecutionEngine.IWxePage currentPage) {
            return PickLocation.Call(currentPage, Remotion.Web.ExecutionEngine.WxeCallArguments.Default);
        }
    }
    
    [System.SerializableAttribute()]
    public class PickLocationFunction : PhoneBook.Web.Classes.BaseFunction {
        
        private Remotion.Web.ExecutionEngine.WxePageStep Step1 = new Remotion.Web.ExecutionEngine.WxePageStep("UI\\PickLocation.aspx");
        
        public PickLocationFunction() : 
                base(new object[0]) {
        }
        
        [Remotion.Web.ExecutionEngine.WxeParameterAttribute(0, Remotion.Web.ExecutionEngine.WxeParameterDirection.Out)]
        public Location ReturnValue {
            get {
                return ((Location)(this.Variables["ReturnValue"]));
            }
        }
    }
}
namespace PhoneBook.Web.UI {
    using System;
    using Remotion.Data.DomainObjects;
    using Remotion.Data.DomainObjects.Queries;
    using Remotion.Web.ExecutionEngine;
    using Remotion.Web.UI.Controls;
    using Remotion.Web.UI.Globalization;
    using Remotion.ObjectBinding;
    using Remotion.ObjectBinding.Web.UI.Controls;
    using Remotion.Data.DomainObjects.ObjectBinding;
    using PhoneBook.Web;
    using PhoneBook.Web.Classes;
    using PhoneBook.Domain;
    
    
    public partial class SearchResultLocationForm {
        
        protected new SearchResultLocationFormFunction CurrentFunction {
            get {
                return ((SearchResultLocationFormFunction)(base.CurrentFunction));
            }
        }
        
        public IQuery query {
            get {
                return ((IQuery)(this.Variables["query"]));
            }
            set {
                this.Variables["query"] = value;
            }
        }
        
        public DomainObjectCollection searchResult {
            get {
                return ((DomainObjectCollection)(this.Variables["searchResult"]));
            }
            set {
                this.Variables["searchResult"] = value;
            }
        }
        
        protected void Return() {
            this.ExecuteNextStep();
        }
        
        public static void Call(Remotion.Web.ExecutionEngine.IWxePage currentPage, Remotion.Web.ExecutionEngine.IWxeCallArguments arguments, IQuery query) {
            SearchResultLocationFormFunction function;
            if ((currentPage.IsReturningPostBack == false)) {
                function = new SearchResultLocationFormFunction(query);
                function.ExceptionHandler.SetCatchExceptionTypes(typeof(System.Exception));
                currentPage.ExecuteFunction(function, arguments);
                throw new System.Exception("(Unreachable code)");
            }
            else {
                function = ((SearchResultLocationFormFunction)(currentPage.ReturningFunction));
                if ((function.ExceptionHandler.Exception != null)) {
                    throw function.ExceptionHandler.Exception;
                }
            }
        }
        
        public static void Call(Remotion.Web.ExecutionEngine.IWxePage currentPage, IQuery query) {
            SearchResultLocationForm.Call(currentPage, Remotion.Web.ExecutionEngine.WxeCallArguments.Default, query);
        }
    }
    
    [System.SerializableAttribute()]
    public class SearchResultLocationFormFunction : PhoneBook.Web.Classes.BaseFunction {
        
        private Remotion.Web.ExecutionEngine.WxePageStep Step1 = new Remotion.Web.ExecutionEngine.WxePageStep("UI\\SearchResultLocationForm.aspx");
        
        public SearchResultLocationFormFunction() : 
                base(new object[0]) {
        }
        
        public SearchResultLocationFormFunction(IQuery query) : 
                base(new object[] {
                            query}) {
        }
        
        [Remotion.Web.ExecutionEngine.WxeParameterAttribute(0, Remotion.Web.ExecutionEngine.WxeParameterDirection.In)]
        public IQuery query {
            set {
                this.Variables["query"] = value;
            }
        }
    }
}
namespace PhoneBook.Web.UI {
    using System;
    using Remotion.Data.DomainObjects;
    using Remotion.Data.DomainObjects.Queries;
    using Remotion.Web.ExecutionEngine;
    using Remotion.Web.UI.Controls;
    using Remotion.Web.UI.Globalization;
    using Remotion.ObjectBinding;
    using Remotion.ObjectBinding.Web.UI.Controls;
    using Remotion.Data.DomainObjects.ObjectBinding;
    using PhoneBook.Web;
    using PhoneBook.Web.Classes;
    using PhoneBook.Domain;
    
    
    public partial class SearchResultPersonForm {
        
        protected new SearchResultPersonFormFunction CurrentFunction {
            get {
                return ((SearchResultPersonFormFunction)(base.CurrentFunction));
            }
        }
        
        public IQuery query {
            get {
                return ((IQuery)(this.Variables["query"]));
            }
            set {
                this.Variables["query"] = value;
            }
        }
        
        public DomainObjectCollection searchResult {
            get {
                return ((DomainObjectCollection)(this.Variables["searchResult"]));
            }
            set {
                this.Variables["searchResult"] = value;
            }
        }
        
        protected void Return() {
            this.ExecuteNextStep();
        }
        
        public static void Call(Remotion.Web.ExecutionEngine.IWxePage currentPage, Remotion.Web.ExecutionEngine.IWxeCallArguments arguments, IQuery query) {
            SearchResultPersonFormFunction function;
            if ((currentPage.IsReturningPostBack == false)) {
                function = new SearchResultPersonFormFunction(query);
                function.ExceptionHandler.SetCatchExceptionTypes(typeof(System.Exception));
                currentPage.ExecuteFunction(function, arguments);
                throw new System.Exception("(Unreachable code)");
            }
            else {
                function = ((SearchResultPersonFormFunction)(currentPage.ReturningFunction));
                if ((function.ExceptionHandler.Exception != null)) {
                    throw function.ExceptionHandler.Exception;
                }
            }
        }
        
        public static void Call(Remotion.Web.ExecutionEngine.IWxePage currentPage, IQuery query) {
            SearchResultPersonForm.Call(currentPage, Remotion.Web.ExecutionEngine.WxeCallArguments.Default, query);
        }
    }
    
    [System.SerializableAttribute()]
    public class SearchResultPersonFormFunction : PhoneBook.Web.Classes.BaseFunction {
        
        private Remotion.Web.ExecutionEngine.WxePageStep Step1 = new Remotion.Web.ExecutionEngine.WxePageStep("UI\\SearchResultPersonForm.aspx");
        
        public SearchResultPersonFormFunction() : 
                base(new object[0]) {
        }
        
        public SearchResultPersonFormFunction(IQuery query) : 
                base(new object[] {
                            query}) {
        }
        
        [Remotion.Web.ExecutionEngine.WxeParameterAttribute(0, Remotion.Web.ExecutionEngine.WxeParameterDirection.In)]
        public IQuery query {
            set {
                this.Variables["query"] = value;
            }
        }
    }
}
namespace PhoneBook.Web.UI {
    using System;
    using Remotion.Data.DomainObjects;
    using Remotion.Data.DomainObjects.Queries;
    using Remotion.Web.ExecutionEngine;
    using Remotion.Web.UI.Controls;
    using Remotion.Web.UI.Globalization;
    using Remotion.ObjectBinding;
    using Remotion.ObjectBinding.Web.UI.Controls;
    using Remotion.Data.DomainObjects.ObjectBinding;
    using PhoneBook.Web;
    using PhoneBook.Web.Classes;
    using PhoneBook.Domain;
    
    
    public partial class SearchResultPhoneNumberForm {
        
        protected new SearchResultPhoneNumberFormFunction CurrentFunction {
            get {
                return ((SearchResultPhoneNumberFormFunction)(base.CurrentFunction));
            }
        }
        
        public IQuery query {
            get {
                return ((IQuery)(this.Variables["query"]));
            }
            set {
                this.Variables["query"] = value;
            }
        }
        
        public DomainObjectCollection searchResult {
            get {
                return ((DomainObjectCollection)(this.Variables["searchResult"]));
            }
            set {
                this.Variables["searchResult"] = value;
            }
        }
        
        protected void Return() {
            this.ExecuteNextStep();
        }
        
        public static void Call(Remotion.Web.ExecutionEngine.IWxePage currentPage, Remotion.Web.ExecutionEngine.IWxeCallArguments arguments, IQuery query) {
            SearchResultPhoneNumberFormFunction function;
            if ((currentPage.IsReturningPostBack == false)) {
                function = new SearchResultPhoneNumberFormFunction(query);
                function.ExceptionHandler.SetCatchExceptionTypes(typeof(System.Exception));
                currentPage.ExecuteFunction(function, arguments);
                throw new System.Exception("(Unreachable code)");
            }
            else {
                function = ((SearchResultPhoneNumberFormFunction)(currentPage.ReturningFunction));
                if ((function.ExceptionHandler.Exception != null)) {
                    throw function.ExceptionHandler.Exception;
                }
            }
        }
        
        public static void Call(Remotion.Web.ExecutionEngine.IWxePage currentPage, IQuery query) {
            SearchResultPhoneNumberForm.Call(currentPage, Remotion.Web.ExecutionEngine.WxeCallArguments.Default, query);
        }
    }
    
    [System.SerializableAttribute()]
    public class SearchResultPhoneNumberFormFunction : PhoneBook.Web.Classes.BaseFunction {
        
        private Remotion.Web.ExecutionEngine.WxePageStep Step1 = new Remotion.Web.ExecutionEngine.WxePageStep("UI\\SearchResultPhoneNumberForm.aspx");
        
        public SearchResultPhoneNumberFormFunction() : 
                base(new object[0]) {
        }
        
        public SearchResultPhoneNumberFormFunction(IQuery query) : 
                base(new object[] {
                            query}) {
        }
        
        [Remotion.Web.ExecutionEngine.WxeParameterAttribute(0, Remotion.Web.ExecutionEngine.WxeParameterDirection.In)]
        public IQuery query {
            set {
                this.Variables["query"] = value;
            }
        }
    }
}
