//------------------------------------------------------------------------------
// Generated by UIGen as workaround for "Custom Tool" laziness. Will be
// overwritten when user saves corresponding .ascx or .aspx file!
//------------------------------------------------------------------------------

namespace PhoneBook.Web.UI
{
	public partial class EditLocationControl
	{
		protected global::Remotion.ObjectBinding.Web.UI.Controls.BindableObjectDataSourceControl CurrentObject;
		protected global::Remotion.Web.UI.Controls.FormGridManager FormGridManager;
		protected global::System.Web.UI.HtmlControls.HtmlTable LocationFormGrid;
		// protected Remotion.Web.UI.Controls.FormGridLabel LocationGridLabel;

    
	}
}
