//------------------------------------------------------------------------------
// Generated by UIGen as workaround for "Custom Tool" laziness. Will be
// overwritten when user saves corresponding .ascx or .aspx file!
//------------------------------------------------------------------------------

namespace PhoneBook.Web.UI
{
	public partial class EditPersonForm
	{
		protected global::Remotion.Web.UI.Controls.HtmlHeadContents HtmlHeadContents;
		protected global::Remotion.ObjectBinding.Web.UI.Controls.BindableObjectDataSourceControl CurrentObject;
                protected global::Remotion.Web.UI.Controls.TabbedMultiView MultiView;
		protected global::PhoneBook.Web.UI.NavigationTabs TheNavigationTabs;
		protected global::Remotion.Web.UI.Controls.TabView EditPersonView;
		protected global::PhoneBook.Web.UI.EditPersonControl EditPersonControl;
		protected global::System.Web.UI.HtmlControls.HtmlForm EditForm;
		protected global::Remotion.Web.UI.Controls.WebButton SaveButton;
		protected global::Remotion.Web.UI.Controls.WebButton CancelButton;
	}
}
