//------------------------------------------------------------------------------
// Generated by UIGen as workaround for "Custom Tool" laziness. Will be
// overwritten when user saves corresponding .ascx or .aspx file!
//------------------------------------------------------------------------------

namespace PhoneBook.Web.UI
{
	public partial class EditPersonControl
	{
		protected global::Remotion.ObjectBinding.Web.UI.Controls.BindableObjectDataSourceControl CurrentObject;
		protected global::Remotion.Web.UI.Controls.FormGridManager FormGridManager;
		protected global::System.Web.UI.HtmlControls.HtmlTable PersonFormGrid;
		// protected Remotion.Web.UI.Controls.FormGridLabel PersonGridLabel;

    
	    protected global::Remotion.Web.UI.Controls.SmartLabel PhoneNumbersLabel;
	    protected global::Remotion.ObjectBinding.Web.UI.Controls.BocList PhoneNumbersField;
    
	}
}
