//------------------------------------------------------------------------------
// Generated by UIGen as workaround for "Custom Tool" laziness. Will be
// overwritten when user saves corresponding .ascx or .aspx file!
//------------------------------------------------------------------------------

namespace PhoneBook.Web.UI {
    public partial class NavigationTabs {
        protected Remotion.Web.UI.Controls.TabbedMenu TheTabbedMenu;
    }
}
