//------------------------------------------------------------------------------
// Generated by UIGen as workaround for "Custom Tool" laziness. Will be
// overwritten when user saves corresponding .ascx or .aspx file!
//------------------------------------------------------------------------------

namespace PhoneBook.Web.UI
{
	public partial class SearchResultPhoneNumberForm
	{
		protected Remotion.Web.UI.Controls.HtmlHeadContents HtmlHeadContents;
		protected Remotion.ObjectBinding.Web.UI.Controls.BindableObjectDataSourceControl PhoneNumberSearchDataSource;
		protected Remotion.Web.UI.Controls.FormGridManager FormGridManager;
		protected PhoneBook.Web.UI.NavigationTabs NavigationTabs;
		protected Remotion.ObjectBinding.Web.UI.Controls.BocList PhoneNumberList;
		protected global::System.Web.UI.HtmlControls.HtmlForm SearchResultForm;
	}
}
